apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    csc-owner-name: installed-custom-openshift-operators
    csc-owner-namespace: openshift-marketplace
  name: installed-custom-openshift-operators
  namespace: openshift-operators
spec:
  address: installed-custom-openshift-operators.openshift-marketplace:50051
  displayName: Custom Operators
  icon:
    base64data: ""
    mediatype: ""
  publisher: Custom
  sourceType: grpc
